apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n-ha
stringData:
  DB_USER: n8n
  DB_PASSWORD: n8npass
  DB_NAME: n8n
  REDIS_PASSWORD: redispass
  N8N_JWT_SECRET: superjwtsecret
  N8N_ENCRYPTION_KEY: superencryptionkey