apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
  namespace: n8n-ha
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: n8n
      role: main
  template:
    metadata:
      labels:
        app: n8n
        role: main
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n
        ports:
        - containerPort: 5678
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
        - secretRef:
            name: n8n-secrets
        env:
        - name: N8N_WORKER
          value: "false"
        - name: N8N_HOST
          value: n8n.localhost
        - name: N8N_PROTOCOL
          value: http
        - name: N8N_PORT
          value: "5678"
        - name: N8N_EDITOR_BASE_URL
          value: https://n8n.localhost
        - name: WEBHOOK_URL
          value: https://n8n.localhost
        - name: N8N_SECURE_COOKIE
          value: "true"
        - name: N8N_DIAGNOSTICS_ENABLED
          value: "false"
        - name: DB_POSTGRESDB_HOST
          value: n8n-postgresql-hl.n8n-ha.svc.cluster.local
        - name: REDIS_HOST
          value: n8n-redis-master.n8n-ha.svc.cluster.local
        volumeMounts:
        - name: n8n-storage
          mountPath: /home/node/.n8n
      volumes:
        - name: n8n-storage
          persistentVolumeClaim:
            claimName: n8n-pvc