apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
stringData:
  basic_auth_user: "admin"
  basic_auth_password: "supersecreta123quenoconseguirassacarnunca"
  encryption_key: "A5OVFbb0mTZqNJ9NZVZEWHYUEMcgzpfgpTUd9MJ8LY0="
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: n8n
type: Opaque
data:
  redis-password: c3VwZXJzZWNyZXRwYXNzd29yZA== # <- supersecretpassword