apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: n8n_user
  POSTGRES_PASSWORD: S3cur3P@ssw0rd!notelocreesnitu
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: n8n_user
  POSTGRES_NON_ROOT_PASSWORD: S3cur3P@ssw0rd!notelocreesnitu